### PR TITLE
Update syntax.tex

### PR DESCRIPTION
**Pull request by vawm**
Added a section about choice questions

### CODE REVIEW

**Comment by vawm** [comment]
This would become Horen 6.14.6

**Comment by Txawey** [comment]
this has actually already been added in another location, but will check to see where it fits best and merge if needed.

**Comment by vawm** [comment]
:O
Could you tell me where it is?

**Comment by Txawey** [comment]
it's in the "fu" section, but I like it both sections, so I'm going to merge

**Pull request merged**
